config/routes.rb
App1::Application.routes.draw do
  get "demo/index"
  get "demo/index2"
  get "demo/index3"

  
  resources :pins

  devise_for :users

  get 'about' => 'pages#about'

  root :to => 'pins#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/pin.rb
class Pin < ActiveRecord::Base
  attr_accessible :description , :image, :image_remote_url #, :string

  validates :description, presence: true
  validates :user_id, presence: true
  validates_attachment :image, presence: true,
                            content_type: { content_type: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif'] },
                            size: { less_than: 5.megabytes }
  belongs_to :user
  has_attached_file :image, styles: { medium: "320x240>"}
  
  def image_remote_url=(url_value)
  	self.image = URI.parse(url_value) unless url_value.blank?
  	super
  end

  def abc
    
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         # :recoverable, 
         :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  # attr_accessible :title, :body

  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/demo_controller.rb
class DemoController < ApplicationController
  def index
  end

  def index2
  end

  def index3
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

  def action
  end

  def step1		
  end

  def step2		
  end

  def step3	
    gb = Gibbon.new("8474dfd72a38461ac6219dfa72f558f1-us7")
    
    @list = gb.lists
      
  end

  def step4		
  end

  def step5		
  end    

  def step6		
  end

  def step7		
  end

end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_filter :authenticate_user!, except: [:index]

  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.order("created_at desc").page(params[:page]).per_page(20)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pins }
    end
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
    @pin = Pin.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pin }
    end
  end

  # GET /pins/new
  # GET /pins/new.json
  def new
    # @pin = Pin.new
    @pin = current_user.pins.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pin }
    end
  end

  # GET /pins/1/edit
  def edit
    @pin = current_user.pins.find(params[:id])
  end

  # POST /pins
  # POST /pins.json
  def create
    # c@pin = Pin.new(params[:pin])
    @pin = current_user.pins.new(params[:pin])
    
    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render json: @pin, status: :created, location: @pin }
      else
        format.html { render action: "new" }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pins/1
  # PUT /pins/1.json
  def update
    @pin = Pin.find(params[:id])

    respond_to do |format|
      if @pin.update_attributes(params[:pin])
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin = current_user.pins.find(params[:id])
    @pin.destroy

    respond_to do |format|
      format.html { redirect_to pins_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

 def full_title(page_title)
 	base_title = "Ruby on Rails App1"
 	if page_title.empty?
 		base_title
 	else
 		"#{base_title} | #{page_title}"
 	end
 end
end

app/helpers/demo_helper.rb
module DemoHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/demo/index.html.erb
<!-- QQDD generated demo -->
<body data-spy="scroll" data-target=".bs-docs-sidebar" data-twttr-rendered="true">

	<div class = "container">
		<h1>Demo Title</h1>
			<div class = "row">

				<div class = "span8">
					<div class = "hero-unit">
						<section id = "step-1">
			                <div class = "page-header"><h1>STEP1</h1>
			                </div>	
			                <p class = "lead">111</p>
			                <hr>
			            
						</section>
						
						<section id = "step-2">
		                	<div class = "page-header"><h1>STEP2</h1>
			                </div>	
			                <p class = "lead">222</p>
			                <hr>
			            
						</section>

						<section id = "step-3">
			                <div class = "page-header"><h1>STEP3</h1>
			                </div>	
			                <p class = "lead">333</p>
			                <hr>
			            
						</section>

						<section id = "step-4">
			                <div class = "page-header"><h1>STEP4</h1>
			                </div>	
			                <p class = "lead">444</p>
			                <hr>
			            
						</section>

						<section id = "step-5">
			                <div class = "page-header"><h1>STEP5</h1>
			                </div>	
			                <p class = "lead">555</p>
			                <hr>
						</section>				
			        </div>
				</div>
                

                <div class = "span2 bs-docs-sidebar pull-right">
				  
					<ul class = "nav nav-list bs-docs-sidenav affix">
					   		
							<li class = "nav-header">STEPS</li>
								<li><%= link_to "Step 1", "#step-1" %></li>
								<li><%= link_to "Step 2", "#step-2" %></li>
								<li><%= link_to "Step 3", "#step-3" %></li>
								<li><%= link_to "Step 4", "#step-4" %></li>
								<li><%= link_to "Step 5", "#step-5" %></li>
								<li><%= link_to "Step 6", "#" %></li>
								<li><%= link_to "Step 7", "#" %></li>
								<li><%= link_to "Step 8", "#" %></li>
					   
					</ul>
				  </div>					
				
			</div>
	</div>
</body>

app/views/demo/index2.html.erb
<%= render :partial => "pages/step1"%>

app/views/layouts/_footer.html.erb
<div class="footer">
	<hr>
    <small>
    	RoR by <big>Qidi</big>
    </small>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
 
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
 
      <!-- Be sure to leave the brand out there if you want it shown -->
      <%= link_to "Qidi's App1", root_path, class: "brand" %>
      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse collapse">
      	
        <!-- .nav, .navbar-search, .navbar-form, etc -->
	  	<ul class="nav">
	  		<li><%= link_to "HOME", root_path %></li>
	    	<li><%= link_to "ABOUT", about_path %></li>

        <!-- QQDD: Add demo tag, leading to /demo/index -->
        <li><%= link_to "DEMO", { :controller => "/demo", :action => "index" } %></li>
		    <li><%= link_to "DEMO2", { :controller => "/pages", :action => "step1" } %></li>
        <li><%= link_to "DEMO3", { :controller => "/demo", :action => "index3" } %></li>
        <li><%= link_to "resume", { :controller => "/pages", :action => "step2" } %></li>
        <li><%= link_to "mailchimp", { :controller => "/pages", :action => "step3" } %></li>
    </ul>
			  	<ul class="nav pull-right">
	  		<% if user_signed_in? %>
        <li><%= link_to "Add+", new_pin_path %></li>
        <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
        <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
		</ul>
      </div>
 
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title><%= full_title(yield (:title)) %></title>
	  <%= stylesheet_link_tag  "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>

	  <link href="css/bootstrap.min.css" rel="stylesheet" media="screen">
	</head>

	<body>		 
		 <div class="container">
		 	<%= render 'layouts/header' %> 
			<% flash.each do |name, msg| %>
				<%= content_tag(:div, msg, class: "alert alert-#{name}") %>
		  <% end %>	
		
	<!-- QQDD yield is for loading the view for the current controller -->
	<%= yield %> 
		 <%= render 'layouts/footer' %>
	</div>
	    <script src="http://code.jquery.com/jquery.js"></script>
    	<script src="js/bootstrap.min.js"></script>
	</body>
</html>

app/views/pages/_home.html.erb
<% unless user_signed_in? %>
	<div class='hero-unit'>
		<h1>Welcome to Qidi's rails world</h1>
		<p>
			A Youtube link is put here!!!
		   <%= link_to "Youtube", "http://www.youtube.com" %>
		</p>
		<p>
			<%= link_to "Sign Up Now!", new_user_registration_path, class: "btn btn-primary btn-large" %>
		</p>
	</div>
<% end %>

app/views/pages/_step-nav.html.erb
<div class = "span2 bs-docs-sidebar pull-right">
				
	    <!--
	    <div class = "well">
			<li class = "nav-header">STEPS</li>
					<li><%= link_to "Step 1", '/step_1' %></li>
					<li><%= link_to "Step 2", '/step_2' %></li>
					<li><%= link_to "Step 3", '#' %></li>
					<li><%= link_to "Step 4", '#' %></li>
					<li><%= link_to "Step 5", '#' %></li>
					<li><%= link_to "Step 6", '#' %></li>
					<li><%= link_to "Step 7", '#' %></li>
					<li><%= link_to "Step 8", '#' %></li>
		</div>
	    
        
        <div class="dropdown">
                  <a class="dropdown-toggle" data-toggle="dropdown" href="#">First<b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li><%= link_to "Step 1", '/step_1' -%></li>
                    <li><%= link_to "Step 2", '/step_2' %></li>
                    <li><%= link_to "Step 3", '#' %></li>
                  </ul>
        </div>

        <div class="dropdown">
                  <a class="dropdown-toggle" data-toggle="dropdown" href="#">Second<b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li><%= link_to "Step 1", '/step_1' -%></li>
                    <li><%= link_to "Step 2", '/step_2' %></li>
                    <li><%= link_to "Step 3", '#' %></li>
                  </ul>
        </div>

                <div class="dropdown">
                  <a class="dropdown-toggle" data-toggle="dropdown" href="#">Third<b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li><%= link_to "Step 1", '/step_1' -%></li>
                    <li><%= link_to "Step 2", '/step_2' %></li>
                    <li><%= link_to "Step 3", '#' %></li>
                  </ul>
        </div>
     -->

  <div class="accordion" id="accordion2">
    <div class="accordion-group">
      <div class="accordion-heading">
        <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
          Collapsible Group Item #1
        </a>
      </div>
      <div id="collapseOne" class="accordion-body collapse">
        <div class="accordion-inner">
          1111111111111111111
        </div>
      </div>
    </div>
    <div class="accordion-group">
      <div class="accordion-heading">
        <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
          Collapsible Group Item #2
        </a>
      </div>
      <div id="collapseTwo" class="accordion-body collapse">
        <div class="accordion-inner">
          222222222222222222222
        </div>
      </div>
    </div>
  </div>

</div>

app/views/pages/about.html.erb
<% provide(:title, 'About') %>
<h1>about</h1>
<p>
	<%= link_to "Yahoo", "http://www.yahoo.com" %>
</p>

app/views/pages/step1.html.erb
<div class = "container">
	<h1>Demo Title</h1>
	<div class = "row">

		<div class = "span8">
			<div class = "hero-unit">

			<%= "S T E P 1" %>

			</div>
		</div>

		<%= render :partial => "pages/step-nav"%>

	</div>

</div>

app/views/pages/step3.html.erb
<div class = "container">
	<h1>Mailchimp Demo</h1>
	<div class = "row">

		<div class = "span8">
			<div class = "hero-unit">

              <%= @list %>

			</div>
		</div>


	</div>

</div>

app/views/pages/step4.html.erb
<div class = "container">
	<h1>Demo Title</h1>
	<div class = "row">

		<div class = "span8">
			<div class = "hero-unit">

			<%= "S T E P 4" %>

			</div>
		</div>

		<%= render :partial => "pages/step-nav"%>

	</div>

</div>

app/views/pages/step5.html.erb
<div class = "container">
	<h1>Demo Title</h1>
	<div class = "row">

		<div class = "span8">
			<div class = "hero-unit">

			<%= "S T E P 5" %>

			</div>
		</div>

		<%= render :partial => "pages/step-nav"%>

	</div>

</div>

app/views/pages/step6.html.erb
<div class = "container">
	<h1>Demo Title</h1>
	<div class = "row">

		<div class = "span8">
			<div class = "hero-unit">

			<%= "S T E P 6" %>

			</div>
		</div>

		<%= render :partial => "pages/step-nav"%>

	</div>

</div>

app/views/pages/step7.html.erb
<div class = "container">
	<h1>Demo Title</h1>
	<div class = "row">

		<div class = "span8">
			<div class = "hero-unit">

			<%= "S T E P 7" %>

			</div>
		</div>

		<%= render :partial => "pages/step-nav"%>

	</div>

</div>

app/views/pins/_form.html.erb
<%= simple_form_for(@pin, html: { class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>

  <%= f.full_error :image_file_size, class: "alert alert-error" %>
  <%= f.full_error :image_content_type, class: "alert alert-error" %>

  <%= f.input :image, label: "Upload an image" %>

  <%= f.input :image_remote_url, label: "or enter a URL" %>

  <%= f.input :description, as: :text, input_html: {rows: "5"} %>

  <!-- <%= f.input :abc, as: :text, input_html: {rows: "10"} %> <!-- define abc action in /model/pin.rb --> 

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pins/_pin.html.erb
<div class="box">
    <%= link_to (image_tag pin.image(:medium)), pin %>
    <p class="description">
        <%= pin.description %>
    </p>
    <p>
        <strong>
            Posted by <%= pin.user.name %>
        </strong>
    </p>
    <% if current_user == pin.user %>
        <p>
          <%= link_to 'Edit', edit_pin_path(pin) %>
          <%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %>
        </p>
    <% end %>
</div>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<!-- 

<h1>Listing pins</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Description</th>
      <th>String</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <%= render @pins %>
  </tbody>

</table>


<%= link_to 'New Pin', new_pin_path %>
<br />
-->

<%= render 'pages/home' %>

<div id="pins">
  <%= render @pins %>
</div>

<%= will_paginate @pins %>

app/views/pins/new.html.erb
<h1>New pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<!-- ><p id="notice"><%= notice %></p> -->
<div class="row">
	<div class="span6 offset3">
		<div class="well">
			<%= image_tag @pin.image %>
			<p>
			  <b>Description:</b>
			  	<%= @pin.description %>
			</p>
			<p>
			  <b>User Name</b>
			  	<%= @pin.user.name %>
			</p>
			<% if current_user == @pin.user %>
				<%= link_to 'Edit', edit_pin_path(@pin) %> |
			<% end %>
				<%= link_to 'Back', pins_path %>
		</div>
	</div>
</div>
<!-- <p>
  <b>String:</b>
  <%= @pin.string %>
</p>
-->